name: Apple Clang

on:
  workflow_dispatch: 

jobs:
  apple-clang:
    uses: ./.github/workflows/build.yml
    with:
      os: macos-latest
      generator: Ninja
      cmake_args: "-DCMAKE_BUILD_TYPE=Debug"
